# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gittis Lab Website
email: your-email@domain.com
description: Welcome to the Gittis Lab at Carnegie Mellon University. Our main objective is to understand how distinct 
  cell types in the basal ganglia wire up and communicate to regulate behavior in health and disease. 
  We utilize genetic and molecular tools to target and manipulate distinct neural circuits in acute slices and awake behaving animals. 
  Experimental approaches include electrophysiology, optogenetics, histology, and behavior.
  Postdoctoral positions are now available, please contact Dr. Aryn Gittis (agittis@cmu.edu).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
